journal:
  name: api-gateway.journal
server:
  port: ${PORT:2000}
spring:
  jackson:
    time-zone: UTC
redis:
  host: ${REDIS_HOST:localhost}
  port: ${REDIS_PORT:6379}
  expiretime: 100
  password:
endpoints:
  users:
    host: ${USERS_SERVICE_HOST:http://localhost:8082}/v1/user
    username: ${USERS_SERVICE_USERNAME:user_service}
    password: ${USERS_SERVICE_PASSWORD:password}
  token:
    host: ${TOKENS_SERVICE_HOST:http://localhost:8084}/v1/tokens
    username: ${TOKENS_SERVICE_USERNAME:tokens_service}
    password: ${TOKENS_SERVICE_PASSWORD:password}
  configuration:
    host: ${CONFIG_SERVICE_HOST:http://localhost:8083}/v1/config
    username: ${CONFIG_SERVICE_USERNAME:config_service}
    password: ${CONFIG_SERVICE_PASSWORD:password}
  public_keys:
    host: ${CONFIG_SERVICE_HOST:http://localhost:8083}/v1/public-key
    username: ${CONFIG_SERVICE_USERNAME:config_service}
    password: ${CONFIG_SERVICE_PASSWORD:password}
  notifications:
    host: ${USERS_SERVICE_HOST:http://localhost:8082}/v1/notifications
    username: ${USERS_SERVICE_USERNAME:user_service}
    password: ${USERS_SERVICE_PASSWORD:password}
  credits:
    host: ${PAYMENTS_SERVICE_HOST:http://localhost:8085}/v1/credits
    username: ${PAYMENTS_SERVICE_USERNAME:payments_service}
    password: ${PAYMENTS_SERVICE_PASSWORD:password}
  credentials:
    host: ${USERS_SERVICE_HOST:http://localhost:8082}/v1/credentials
    username: ${USERS_SERVICE_USERNAME:user_service}
    password: ${USERS_SERVICE_PASSWORD:password}
  configurations:
    host: ${CONFIG_SERVICE_HOST:http://localhost:8083}/v1/config
    username: ${CONFIG_SERVICE_USERNAME:config_service}
    password: ${CONFIG_SERVICE_PASSWORD:password}
  pricing:
    host: ${CONFIG_SERVICE_HOST:http://localhost:8083}/v1/pricing
    username: ${CONFIG_SERVICE_USERNAME:config_service}
    password: ${CONFIG_SERVICE_PASSWORD:password}
  consumption:
    host: ${PAYMENTS_SERVICE_HOST:http://localhost:8085}/v1/consumption
    username: ${PAYMENTS_SERVICE_HOST:http://localhost:8085}/v1/consumption
    password: ${PAYMENTS_SERVICE_HOST:http://localhost:8085}/v1/consumption
  payments:
    host: ${PAYMENTS_SERVICE_HOST:http://localhost:8085}/v1/payments
    username: ${PAYMENTS_SERVICE_USERNAME:payments_service}
    password: ${PAYMENTS_SERVICE_PASSWORD:password}
    schedule-payments-url: ${PAYMENTS_SERVICE_HOST:http://localhost:8085}/schedule
    callback-url: ${PAYMENTS_SERVICE_HOST:http://localhost:8085}/callback
    timeout-url: ${PAYMENTS_SERVICE_HOST:http://localhost:8085}/timeout
    validate-payments-url: ${PAYMENTS_SERVICE_HOST:http://localhost:8085}/validate
    validate-payments-result-url: ${PAYMENTS_SERVICE_HOST:http://localhost:8085}/status
  meters:
    host: ${METERS_SERVICE_HOST:http://localhost:8082}/v1/meters
    username: ${METERS_SERVICE_USERNAME:user_service}
    password: ${METERS_SERVICE_PASSWORD:password}
  subscribers:
    host: ${SUBSCRIBERS_SERVICE_HOST:http://localhost:8082}/v1/subscriber
    username: ${SUBSCRIBERS_SERVICE_USERNAME:user_service}
    password: ${SUBSCRIBERS_SERVICE_PASSWORD:password}
  utilities:
    host: ${UTILITIES_SERVICE_HOST:http://localhost:8082}/v1/utility
    username: ${UTILITIES_SERVICE_USERNAME:user_service}
    password: ${UTILITIES_SERVICE_PASSWORD:password}
management:
  health:
    probes:
      enabled: true
    livenessState:
      enabled: true
    readinessState:
      enabled: true